name: daily
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged
    steps:
      - name: Clone build scripts
        uses: actions/checkout@v1
      - name: Build and upload daily .iso
        run: |
          ./workflows.sh etc/terraform-daily-6.0-azure.conf
      - name: Archive any ISOs
        uses: actions/upload-artifact@v2
        with:
          name: live-image
          path: '**/*.iso'
